export const Student= "المتعلم"
export const AsTutor= "كمدرس"
export const SignUpAsAStudent ="سجل كطالب";
export const SignUpAsATutor ="سجل كمدرس";
export const Forgotpassword ="هل نسيت كلمة السر؟"
export const Home="الصفحة الرئيسية"
export const TermsAndConditions = "البنود و الظروف"
export const ContactUs = "اتصل بنا"
export const Login = "تسجيل الدخول"